export const events = [
  {
    image: '/images/event1.png',
    title: 'Advanced Web Development',
    slug: 'event-1',
    location: 'San Francisco, CA',
    date: '2026-06-15',
    time: '10:00 AM',
  },
  {
    image: '/images/event2.png',
    title: 'AI & Machine Learning Workshop',
    slug: 'event-2',
    location: 'New York, NY',
    date: '2026-07-20',
    time: '2:00 PM',
  },
  {
    image: '/images/event3.png',
    title: 'Blockchain Technology Explained',
    slug: 'event-3',
    location: 'Austin, TX',
    date: '2026-08-10',
    time: '9:00 AM',
  },
  {
    image: '/images/event4.png',
    title: 'React Conference 2026',
    slug: 'event-4',
    location: 'Seattle, WA',
    date: '2026-09-05',
    time: '11:00 AM',
  },
  {
    image: '/images/event5.png',
    title: 'Cybersecurity Summit',
    slug: 'event-5',
    location: 'Boston, MA',
    date: '2026-10-12',
    time: '1:00 PM',
  },
  {
    image: '/images/event6.png',
    title: 'Data Science Bootcamp',
    slug: 'event-6',
    location: 'Chicago, IL',
    date: '2026-11-18',
    time: '8:00 AM',
  },
];